;Exercise 1.9.  Each of the following two procedures defines a method for adding 
;two positive integers in terms of the procedures inc, which increments its 
;argument by 1, and dec, which decrements its argument by 1.
;
;Using the substitution model, illustrate the process generated by each 
;procedure in evaluating (+ 4 5). Are these processes iterative or recursive? 

; These examples use 'o+' as the function name to avoid stepping
; on the function, clojure.core/+
;
(defn o+
  [a b]
  (if (= a 0)
    b
    (inc (o+ (dec a) b))))

; Illustration of the process created by the above procedure.
; This illustrates a procedure that has the shape of linear recursion.
;(+ 4 5)
;(inc (+ 3 5))
;(inc (inc (+ 2 5)))
;(inc (inc (inc (+ 1 5))))
;(inc (inc (inc (inc 5))))
;(inc (inc (inc 6)))
;(inc (inc 7))
;(inc 8)
; 9

(defn o+
  [a b]
  (if (= a 0)
    b
    (o+ (dec a) (inc b))))

; Illustration of the process created by the above procedure.
; This illustrates a procedure that has the shape of iterative recursion.
;(+ 4 5)
;(+ 3 6)
;(+ 2 7)
;(+ 1 8)
; 9
